export { router as achievements } from './achievements';
export { router as cache } from './cache';
export { router as friends } from './friends';
export { router as guild } from './guild';
export { router as home } from './home';
export { router as name } from './name';
export { router as pets } from './pets';
export { router as player } from './player';
export { router as quests } from './quests';